# Gunakan image Dart resmi
FROM dart:stable AS build

# Buat folder kerja di dalam container
WORKDIR /app

# Copy semua file proyek ke dalam container
COPY . .

# Jalankan pub get untuk mengambil dependensi
RUN dart pub get

# Expose port sesuai dengan aplikasi backend-mu
EXPOSE 8080

# Perintah untuk menjalankan aplikasi dari lib/main.dart
CMD ["dart", "lib/main.dart"]
