# Gunakan Dart versi terbaru
FROM dart:3.7.0 AS build

# Setel work directory
WORKDIR /app

# Salin file pubspec untuk mengelola dependensi
COPY pubspec.yaml pubspec.lock /app/

# Jalankan pub get untuk mengunduh dependensi
RUN dart pub get

# Salin semua file proyek ke dalam container
COPY . .

# Kompilasi kode ke executable
RUN dart compile exe bin/backend_api.dart -o bin/server

# Gunakan runtime Dart untuk menjalankan aplikasi
FROM dart:3.7.0 AS runtime

WORKDIR /app

# Salin hasil build dari stage sebelumnya
COPY --from=build /app/bin/server /app/server

# Eksekusi aplikasi
CMD ["/app/server"]
