name: backend_api
description: Backend API untuk Deteksi Campak
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'  # Sesuaikan dengan versi Dart di lokal

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  http: ^1.3.0
  json_annotation: ^4.9.0
  cryptography: ^2.0.5
  

dev_dependencies:
  lints: ^4.0.0  # Gunakan versi yang cocok dengan Dart 3.0.6
  test: ^1.24.0


