name: backend_api
description: Backend API untuk Deteksi Campak
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  http: ^0.13.6
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^4.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0

